block projects
codex-team/hawk.collector pull request #66
Opened 2020-12-29 13:33 UTC by f0m41h4u7

2020-12-29 13:49 UTC, nikmel2803 commented on .env.docker
> +REDIS_SET=
```suggestion
REDIS_SET=DisabledProjectsSet
```
давай добавим значение по дефолту
и мне кажется стоит переменовать переменную, чтобы было лучше понятно что в ней лежит
типо REDIS_DISABLED_PROJECT_SET
ну или мб как-то по другому

2020-12-29 13:49 UTC, nikmel2803 commented on .env.docker
> +REDIS_PASSWORD=
а нельзя разве их в один url объединить? типо `redis://usrname:password@ipaddress:6379`

2020-12-29 13:53 UTC, f0m41h4u7 commented on .env.docker
> +REDIS_PASSWORD=
Насколько понимаю, нет
![image](https://user-images.githubusercontent.com/53977779/103288623-51e9ee80-49f6-11eb-8bf7-62c7483ce9ae.png)

2020-12-29 14:18 UTC, nikmel2803 requested changes
<img width="574" alt="image" src="https://user-images.githubusercontent.com/32655339/103290107-d12cf180-49f9-11eb-834f-2f591966f61b.png">

2020-12-29 14:29 UTC, nikmel2803 commented on pkg/server/errorshandler/handler.go
> +		return ResponseMessage{true, "Project has exceeded the event limit"}
```suggestion
		return ResponseMessage{true, "Project has exceeded the events limit"}
```
может правильнее так?

2020-12-29 14:29 UTC, nikmel2803 approved these changes

2020-12-29 14:39 UTC, n0str approved these changes

2020-12-29 15:55 UTC, nikmel2803 requested changes
- если забаненый проект пытается отправить sourcemap — надо отклонять запрос
- ради теста я вырубил редис, потом спустя некоторое время включил, но коллектор перестал брать из него данные (ждал больше 10ти минут). В итоге забаненный проект мог слать ивенты
- если вырубить редис, то коллектор очищает свой кэш. Надо чтобы он держал свой кэш до следующего обновления и не очищал его, пока снова не подключится к редису

2021-01-14 05:12 UTC, nikmel2803 approved these changes

2021-01-14 06:44 UTC, merged