Implement IP blacklist
codex-team/hawk.collector pull request #76
Opened 2021-04-16 10:05 UTC by f0m41h4u7

resolves #73

* count per-IP requests quantity 
* check if the quantity is above some threshold 
* send notifications in case of exceeding the threshold

2021-04-17 08:08 UTC, n0str requested changes

2021-04-17 08:08 UTC, n0str commented on cmd/config.go
> +	NotifyURL string `env:"NOTIFY_URL"`
Please, modify `env.sample` and `README.md` to describe these parameters

2021-04-22 14:36 UTC, n0str approved these changes

2021-05-21 09:40 UTC, kabachook requested changes
Rebase master
`github.com/cenkalti/backoff` -> `github.com/cenkalti/backoff/v4`

2021-05-21 21:20 UTC, kabachook approved these changes

2021-05-21 21:57 UTC, merged