Change sourcemap to release. Get catcherType from release
codex-team/hawk.collector pull request #78
Opened 2021-04-24 15:13 UTC by n0str

Now sourcemaps are unified as release of any type.
Release message now includes catcherType

2021-04-24 15:20 UTC, f0m41h4u7 approved these changes

2021-04-24 17:39 UTC, GeekaN2 requested changes

2021-04-24 17:39 UTC, GeekaN2 commented on pkg/server/releasehandler/handler.go
> +	messageToSend := ReleaseMessage{ProjectId: projectId, Files: files, Release: release, CatcherType: catcherType}
А коммиты где? Или в другом реквесте сделаешь?

2021-04-29 18:57 UTC, GeekaN2 commented on pkg/server/server.go
> +	s.ReleaseHander = releasehandler.Handler{
```suggestion
	s.ReleaseHandler = releasehandler.Handler{
```

2021-04-29 18:58 UTC, GeekaN2 commented on pkg/server/server.go
> +		s.ReleaseHander.HandleHTTP(ctx)
```suggestion
		s.ReleaseHandler.HandleHTTP(ctx)
```

2021-04-29 19:16 UTC, GeekaN2 commented
Надо в `hawk.registry` добавить очередь `release` и забиндить её к exchange `errors`, или лучше ещё один exchange создать, потому что это не ошибки.

2021-04-29 19:21 UTC, GeekaN2 commented
Формат отправки данные не соответствует формату таска воркера. Оберни твой payload в тип, чтобы получилось
```js
{
  type: 'add-release',
  payload: task_payload
}
```

2021-06-07 18:06 UTC, GeekaN2 approved these changes

2021-06-07 18:08 UTC, merged