Add some curl examples for new release format
codex-team/hawk.collector pull request #83
Opened 2021-07-20 18:01 UTC by n0str

Modified `Request to upload sourcemap` section

2021-07-21 12:51 UTC, ilyamore88 approved these changes

2021-07-21 16:07 UTC, GeekaN2 requested changes
Всё шикарно, надо только чуть подправить и можно будет для для релиз воркера тоже использовать.

2021-07-21 16:07 UTC, GeekaN2 commented on README.md
> +  "catcherType": "errors/golang",
Мы же выпилили catcherType, потому что его можно по jwt токену узнать

2021-07-21 16:07 UTC, GeekaN2 commented on README.md
> +| commits      | raw JSON        | Suspected commits                                   |
А можно ещё формат коммитов описать?

2021-07-23 07:53 UTC, n0str commented on README.md
> +  "catcherType": "errors/golang",
Ты что-то путаешь. CatcherType зашит в протоколе получения ошибки.
И узнать из JWT его нельзя, там внутри только projectId пока что

2021-07-23 09:55 UTC, GeekaN2 approved these changes
As far as I remember, the `commits` field is not optional now, it will be necessary to correct it in the code. Everything else is ok

2021-07-23 10:05 UTC, merged